const express = require('express');
const cors = require('cors');
const rateLimit = require('express-rate-limit');
const { loggerMiddleware } = require('./middlewares/logger-middleware');
const { router: authRoutes } = require('./routes/auth-routes');
const { router: usersRoutes } = require('./routes/users-routes');
const { router: vehiclesRoutes } = require('./routes/vehicles-routes');

// Environment variables for MongoDB connection.
const { CORS_ORIGIN, RATELIMIT_MIN, RATELIMIT_NREQ } = process.env;




// Create the Express application.
exports.app = express();
const app = exports.app;




// Configure CORS.
const corsOptions = {
    origin: CORS_ORIGIN,
    methods: ['GET', 'POST', 'PATCH', 'DELETE', 'OPTIONS']
};
app.use(cors(corsOptions));
app.options('*', cors(corsOptions));




// Configure and use the rate limiter.
const limiter = rateLimit({
    windowMs: RATELIMIT_MIN * 60 * 1000,                            // X minutes.
    max: RATELIMIT_NREQ,                                            // Limit to Y requests per IP every X minutes.
    message: `Too many requests from this IP, try again later.`,
    standardHeaders: true,                                          // Reports rate limits with standard headers.
    legacyHeaders: false,                                           // Disable obsolete headers.
});
app.use(limiter);




// Middleware for logging.
app.use(loggerMiddleware);




// Disable the X-Powered-By header.
app.disable('x-powered-by');




// Middleware for parsing JSON.
app.use(express.json());




// Middleware for handling JSON syntax errors.
app.use((err, req, res, next) => {

    // Check if the error is a SyntaxError and if it was generated by the JSON parser.
    if (err instanceof SyntaxError && err.status === 400 && 'body' in err) {

        console.error({ message: `JSON Syntax Error.`, details: err.message });
        return res.status(400).json({
            message: `Invalid JSON format in the request body.`,
            details: null
        });
    }

    // Pass any other errors to the next error handler.
    next(err);

});




// Routes.
app.use('/api/auth', authRoutes);
app.use('/api/users', usersRoutes);
app.use('/api/vehicles', vehiclesRoutes);
